version: '3.8'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    expose:
      - "8000"
    command: gunicorn -w 4 -b 0.0.0.0:8000 wsgi:server
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_app