version: "3.8"

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    expose:
      - "8000"
    entrypoint: gunicorn -c config.py server:app tokens.txt

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.18.0
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      # use port 5050 instead of default port 80 to avoid IP attack
      - "5050:80"
    depends_on:
      - flask_app

  mongo:
    container_name: mongo
    image: mongo:4.4.2
    volumes:
      - ./mongo/data/db:/data/db # persist data even if container shuts down
    ports:
      - "23579:27017"

  postgres:
    container_name: postgres
    image: postgres:13.1
    volumes:
      - ./postgres/data:/var/lib/postgresql/data # persist data even if container shuts down
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=Alpine123
      - POSTGRES_DB=twitter-api
