version: "3.8"

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    expose:
      - "8000"
    command: gunicorn -c config.py wsgi:server

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.18.0
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_app
