version: "3.8"

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    expose:
      - "8000"
    entrypoint: gunicorn -c config.py server:app tokens.txt

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.18.0
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "5050:5050"
    depends_on:
      - flask_app
